### PR TITLE
Orbit is now able to contain only text content.

### PR DESCRIPTION
**Pull request by suciuvlad**
Orbit is now able to contain only text content. Pass width and height as arguments upon plugin init. Second orbit on the demo page illustrates that.

### CODE REVIEW

**Comment by mkelly12** [comment]
Not sure I understand what the change is here. I see you are passing additional params to orbit, but I don't see them being used in the plugin. What is the changed behavior here?

**Comment by suciuvlad** [comment]
I've tried to use orbit with text content only. The problem was that the width and height is calculated dynamically based on the slide that is an image.

Adding the width and height in the CSS did not fixed that because the width/height was being overwritten in the js file.

I ended up passing the width and height as params and then checking for them(lines 55-60):

if( options.width && options.height ){
  orbit.add(orbitWrapper).width(options.width).height(options.height);
  orbitWidth = orbit.width();
  orbitHeight = orbit.height();
}else{
  // your code here
}

**Comment by mkelly12** [comment]
Sounds like a selector specificity problem. Orbit will detect the size of the slider based on non-image content as well, but the width and height need to be explicitly set for that content.

You can either set the width and height as an inline style (not recommended), or just make sure your style is being applied correctly.

Using the Orbit demo, I removed the image slides, and then added the following to the CSS:

``` css
.orbit .content { width: 1000px; height: 1000px; }
```

This set the content slides to 1,000 x 1,000px, and Orbit detected these dimensions and resized the slider accordingly. If this does not work try using the code from our refactor branch, which is where I tested it. There my be a fix there that is resolving this for me.

**Comment by rodrigoslompo** [comment]
I tested changing the stylo online as suggested but have not had success using only text content without a picture slide that orbit can rely on to restore height. The suggestion to change plugin parameters to allow the height and width seems a good solution.

**Comment by mkelly12** [comment]
Have you tried the latest version of Orbit that is packaged with Foundation? We've moved Orbit to the Foundation repo so that we can better support it going forward.

https://github.com/zurb/foundation

**Comment by rodrigoslompo** [comment]
Hello, I'm actually using the foundation, but the problem in orbit with height in text content persists when there is absence of a slide with only image. I got a solution is not very elegant editing app.js as follows:

``` javascript
$('.orbit').height('300px');
$('#featured').height('300px'); 
$('.orbit-wrapper').height('300px');
```

**Comment by mkelly12** [comment]
That's strange, since adding those styles inline should do exactly the same thing as adding them to the CSS. Maybe try something like:

``` css
.orbit, #featured, .orbit-wrapper { height: 300px !important; }
```

You should not need the !important, but test with both to see if this does the trick.

**Comment by ghost** [comment]
Hi, this last suggestion is the one that did the trick for me.
Still, I wonder if I can get elements in a grid I'm putting inside each slide to be closer to each other...

I'm doing something like this:

```
...
<section class="container">
    <div id="featured" class="row "> 
        <div class="content twelve columns">
             <ul class="block-grid four-up">
                              <li>...</li>
                              <li>...</li>
                              <li>...</li>
                              <li>...</li>
                         </ul>
               </div>
        <div class="content twelve columns">
             <ul class="block-grid four-up">
                              <li>...</li>
                              <li>...</li>
                              <li>...</li>
                              <li>...</li>
                         </ul>
               </div>
        </div>
</section>
...
```

So basically I'm trying to create a grid similar to the one we see in google chrome but with a different purpose. 
The elements inside each list just get too far apart from each other, and if I try to use the same kind of setting shown in the last comment to define some width it still doesn't work out quite nicely.

Would be kind of cool to define some setting for a slide but get the content inside to accomodate a little bit better.
And I also wonder why %s are not working, I would rather use relative sizes than pixels.

**Pull request closed without merging**
