### PR TITLE
Vertical Push Option

### PR DESCRIPTION
**Pull request by lukemcdonald**
I had a use for this and figured since there was a horizontal push, there may as well be a vertical push.

### CODE REVIEW

**Comment by bjrn** [comment]
ah... +1 for this one, was just about to make a fork and do a pull request, but now I don't need to

**Comment by chaosavatar** [comment]
not working  for me :-(.
downloaded the last version.
 then:
<script type="text/javascript">

```
        $(window).load(function() {
        $('#featured').orbit({
 animation: 'vertical-push',                  // fade, horizontal-slide, vertical-slide, horizontal-push
 animationSpeed: 800,                // how fast animtions are
 timer: true,            // true or false to have the timer
 advanceSpeed: 6000,         // if timer is enabled, time between transitions 
 pauseOnHover: true,         // if you hover pauses the slider
 startClockOnMouseOut: true,     // if clock should start on MouseOut
 startClockOnMouseOutAfter: 10,      // how long after MouseOut should the timer start again
 directionalNav: false,          // manual advancing directional navs
 captions: false,            // do you want captions?
 captionAnimation: 'fade',       // fade, slideOpen, none
 captionAnimationSpeed: 800,     // if so how quickly should they animate in
 bullets: false,             // true or false to activate the bullet navigation
 bulletThumbs: false,        // thumbnails for the bullets
 bulletThumbLocation: '',        // location from this file where thumbs will be
 afterSlideChange: function(){}      // empty function 
```

})
});

and nothing happens. images just change with no animation at all.

**Comment by bjrn** [comment]
@chaosavatar, this is just a pull request, I believe it hasn't been merged with the project yet. You can however still use it by updating your local version with the code found in this pull request

**Comment by mkelly12** [comment]
Thanks for the pull request. This has been committed and will go out with our next release.
9a761b312f3d74108bcccdd8dcfd6c75d636f2df

**Pull request closed without merging**
