### PR TITLE
Fading in and out of nav buttons on mouseover

### PR DESCRIPTION
**Pull request by cpres**
just some easy jQuery for adding opacity and having a fade in fade out component.

### CODE REVIEW

**Comment by mkelly12** [comment]
Hey cpres, thanks for the pull request. 

The code's solid, but I not sure if this is a feature everyone will want. Rather then adding it to the plugin, you could bind to the right and left buttons with `$.fn.live()` and keep the effect you added in your own code. Or use the nice fork you created.

Thanks!

**Comment by cpres** [comment]
Good call on $.fn.live(), I wasn't aware of that function. I will add that
feature in that way. And sadly the fork I created was off the old js, the
1.3.0 seems very new and improved

**Comment by aziele** [comment]
Hello, 

could you provide an example how to show/hide nav arrows on mouseover?

Thank you.

**Comment by aziele** [comment]
I tried to implement showing/hiding nav buttons:

http://jsfiddle.net/sherlock85/mZYX9/15/

but when I move my mouse cursor over a button it blinks and does not work properly.

**Comment by mkelly12** [comment]
You'll need to add !important to the CSS declaration since we running $.fn.show() on the nav buttons.

http://jsfiddle.net/mZYX9/17/

**Comment by nomiDesigns** [comment]
Navigation won't show after adding !important.

**Comment by nomiDesigns** [comment]
NVM, someone here http://j.mp/w4VWYI suggested targeting slider-nav hover as well and it worked like a charm
http://jsfiddle.net/mZYX9/54/

**Comment by Firestorm-Graphics** [comment]
nomi49 , bit late i know, the script you point to is short of one thing, as it stands the nav arrows display on page load and only hide on hover, to correct this and have them hidden on load and only appear on hover, add $("div.slider-nav").hide(); to the top line of the custom script. also might be worth targeting the left and right seperately using:

div.slider-nav span.right,
 div.slider-nav span.left

**Pull request closed without merging**
